--- 
framework: mocha
postMerge: 
  pattern: 
    - "test/**/*.spec.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "test/**/*.spec.js"
preRun: 
  command: 
    - npm ci
    
    
    
#testing  tas    1 
#commiting to test
#testing 2 3 4
